"""
Generate a chunky pixel-art thought-cloud PNG.

Output: /app/frontend/src/assets/thought_cloud.png

92×24 pixel grid: 6 rows of puffs at top + 14 rows of white body + 4 rows of
rounded-bottom outline. NO trailing blank rows so the cloud stretches edge-to-edge
without leaving transparent strips below the body.
"""
from __future__ import annotations
import numpy as np
from PIL import Image

# 92 cols × 24 rows. Designed so every row has SOMETHING (no empty trailing rows).
GRID = """\
.....BBB.........BBBBBB............BBBB................BBB.........BBB................
....BWWWB.......BWWWWWWB..........BWWWWB..............BWWWB.......BWWWB...............
...BWWWWWB.....BWWWWWWWWB........BWWWWWWB............BWWWWWB.....BWWWWWB..............
..BWWWWWWWB...BWWWWWWWWWWB......BWWWWWWWWB..........BWWWWWWWB..BWWWWWWWB..............
.BWWWWWWWWWBBBBWWWWWWWWWWWBBBBBBBWWWWWWWWWBBBBBBBBBBBBWWWWWWWWBBBWWWWWWWWBBBBBBBBBBBBBBB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB
BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB
.BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB.
..BBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWBB..
...BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB...
"""

rows = [r for r in GRID.split("\n") if r]
W = max(len(r) for r in rows)
H = len(rows)
canvas = np.zeros((H, W, 4), dtype=np.uint8)
for ry, row in enumerate(rows):
    s = (row + "." * W)[:W]
    for cx, ch in enumerate(s):
        if ch == "B":
            canvas[ry, cx] = (0, 0, 0, 255)
        elif ch == "W":
            canvas[ry, cx] = (255, 255, 255, 255)
        else:
            canvas[ry, cx] = (0, 0, 0, 0)

img = Image.fromarray(canvas, "RGBA")
img.save("/app/frontend/src/assets/thought_cloud.png")
print(f"Saved cloud {img.size} → /app/frontend/src/assets/thought_cloud.png")
